### ISSUE TITLE
Not compatible with Bolt 3.2.2

### ISSUE THREAD

**Issue by graham73may** [SahAssar/bolt-editcontentcustomtabs#2]
Hi SahAssar,

I've installed v.1.0.0 on Bolt 3.2.2 but get errors with $app:

![image](https://cloud.githubusercontent.com/assets/6642498/21009358/1bd448de-bd3e-11e6-96c0-d6acc1cb5201.png)

I edited the extension to use Silex/Application and the process get's a bit further but runs into more issues.  I then went through and edited the $contenttype to be /Bolt/Storage/Mapping/ContentType instead of an array but the way the code handles this would all need to change as well.

**Comment by SahAssar** [comment]
Should be fixed in `1.1.0`, please reopen if that isn't the case!
