### ISSUE TITLE
[Enhancement] One way relationships get added to META tab

### ISSUE THREAD

**Issue by eduardomart** [SahAssar/bolt-editcontentcustomtabs#4]
Also something discussed in Slack that could use a little enhancement.

Normally in Bolt, when a one-way relationship is created, the other end creates a *relationships* tab that lists the items that point to the record being viewed.

When using editcustomcontenttabs however, adding a new tab that takes fields off from the relationships tab and puts them in the custom tab, causes the opposite end (described above) to list the relationships in the Meta tab, seen here:

![2017-03-01 11-38-33](https://cloud.githubusercontent.com/assets/1833020/23486518/74c1b4b6-fe95-11e6-9b63-7dad01b508c3.png)

My two cents: would be nice to be able to create a tab on the opposite record, or just use the default
*relationships* tab.

**Comment by SahAssar** [comment]
Fixed in 049953a943c50fcbb6b5684ccc0e260bc6914dda
